tinyMCE.addI18n('en.dzcp',{
  title : 'Insert smiley',
  desc : 'Smileys',
  fldesc : 'Flags',
  fltitle : 'Insert flags',
  php_desc : 'PHP Syntax highlighting',
  php_title : 'Paste the PHP-Code into the window.<br />The code will be highlighted after your post from DZCP-Script!',
  insertcode_desc : 'Insert Source code',
  insertcode_title : 'Paste the Source code into the window.',  
  users : 'Insert DZCP users',
  users_all : 'Show all registered users',
  users_clan : 'Show members only',
  users_add_en : 'Insert ',
  users_add_de : ' ',
  clip : 'Instert Clip',
  picupload_desc : 'Upload a picture to this server',
  clip_link : 'Clip Link',
  clip_missing_link : 'You have to insert a link for the clip!',
  youtube: 'Insert Youtube Video',
  youtube_missing_link : 'You have to insert a link to the youtube video!',
  youtube_link: 'Youtube-Link',
  googlevideo: 'Insert Google Video',
  googlevideo_missing_link : 'You have to insert a id from google video!',
  googlevideo_link: 'Google-Video-ID',
  myvideo: 'Insert MyVideo',
  myvideo_missing_link : 'You have to insert a id from video!',
  myvideo_link: 'MyVideo-ID',
  vimeo: 'Insert Vimeo Video',
  vimeo_missing_link : 'You have to insert a id from video!',
  vimeo_link: 'Vimeo-ID',  
  xfire: 'Insert XFire Video',
  xfire_missing_link : 'You have to insert a id from video!',
  xfire_link: 'XFire Video-ID',    
  gt: 'Insert Game Trailers Video',
  gt_missing_link : 'You have to insert a id from video!',
  gt_link: 'Game Trailers Video-ID',
  divx: 'Instert DivX Video',
  divx_link: 'DivX Video URL',
  divx_missing_link : 'You have to insert a link to the Video File!',
  golemvideo: 'Insert Golem Video',
  golemvideo_missing_link : 'You have to insert a id from Golem video!',
  golemvideo_link: 'Golem-Video-ID'
});